### ISSUE TITLE
testing for NSEC records denying things which should exist

### ISSUE THREAD

**Issue by quite** [dnsviz/dnsviz#51] opened 2019-04-04 11:15 UTC
I recently came across a couple of authorative nameservers which somehow presented an NSEC record which declared that the whole zone it was authorative for was empty (denying the existance of itself, being in-bailiwick!). Combined with knot-resolver's aggressive caching using DNSSEC-records, lookups of records at the domains that these nameservers were supposed to be authorative for could not be resolved.

I'm not that familiar with DNSSEC and found help from https://gitter.com/CZ-NIC/knot-resolver. I could see in logs from knot-resolver that it could not find any `NS with an address` (what I did not react to at the time was the `NSEC sname: covered by: example.com. -> example.com.` -- that was probably a great clue!)

Eventually @vcunat found `example.com. NSEC example.com.`, and I could contact the admin who corrected the problem.

Could dnsviz highlight these kind of problems?

As @pspacek said in the discussion: 

> It would be also useful to test for other contradictory answers, e.g. server answering test.example.com. Abut providing proof-of-nonexistence for query test.example.com. TXT which states that test.example.com. A does not exist etc.
In general proofs from NSEC records must not contradict existence of other data which were obtained during the test.

**Comment by cdeccio** [comment] 2019-04-04 12:58
Could you point me to the URL of the DNSViz analysis that didn't catch the problem?

**Comment by quite** [comment] 2019-04-04 14:12
http://dnsviz.net/d/ns1.br3in.nl/dnssec/ -- but i

**Comment by cdeccio** [comment] 2019-04-04 14:19
There's a bit more here:

http://dnsviz.net/d/ns1.br3in.nl/XKGqww/dnssec/?rr=all&a=all&ds=all&doe=on&ta=.&tk=

**Comment by vcunat** [comment] 2019-04-04 16:02
Yes, but ideally `ns1.br3in.nl/A` wouldn't be green in there, as it's denied by NSEC returned in _another_ answer.  I understand it might be complicated to implement such cross-answer checks, though.

**Comment by pspacek** [comment] 2019-04-05 08:24
Another example of a lurking problem is
http://dnsviz.net/d/www.servis24.cz/XKcQeg/dnssec/

Query for `www.servis24.cz AAAA` returns NSEC RR which claims what only TXT type exists but in fact query for `www.servis24.cz A` returns proper answer. This is also a bug in NSEC3 chain.

**Comment by vcunat** [comment] 2019-04-05 09:23
Oh, that's quite a common problem we've seen on [multiple places](https://github.com/dns-violations/dns-violations/blob/master/2018/DVE-2018-0003.md), due to certain software consistently producing it.  They apparently haven't managed to fix the SW for about a year now, but I don't know if redness in DnsViz.net could help to move them...

**Comment by pspacek** [comment] 2019-04-05 16:15
At least it would help with diagnostics when someone complains about DNS problems.

**Comment by cdeccio** [comment] 2019-04-05 17:41
Thanks, all, for the feedback.  I'll take a look in the next few days or so to see if I can make these errors more understandable/noticeable.

**Comment by cdeccio** [comment] 2020-06-16 13:06
Sorry that it's taken so long to circle back on this.  I wanted to take another look, but now I seem to be missing a use case again.  Any chance there is something fresh that you could point me to?

**Comment by vcunat** [comment] 2020-06-16 14:48
I'm currently not aware of any such names alive.  (I'm not searching for them, though.)

**Comment by vcunat** [comment] 2020-06-16 14:56
An analogy of `www.servis24.cz` is still alive on `www.csas.cz`.  In the NODATA answer for AAAA you get denial of all types except TXT (by an NSEC3 with minimal range), but on explicit A request you get signed records.

_I wanted to link to dnsviz, but I can't see those NSEC3 records even shown anywhere in there._

**Comment by cdeccio** [comment] 2020-06-16 15:29
﻿[Here](https://dnsviz.net/d/www.csas.cz/XujdWg/dnssec/?rr=all&a=all&ds=all&doe=on&ta=.&tk=) is the DNSViz link.  Note that the "Denial of existence" box is checked under "DNSSEC options", so the NSEC records are shown.

So to be clear, what's happening is 1) in one response the server claims that A exists (through an actual A record in the response; and 2) in a second response the server claims that A does not exist (i.e., because it doesn't show up in the RR type bitmap).

And also, this is a second problem, which is distinct from, but related to, the problem originally posted, right?

**Comment by vcunat** [comment] 2020-06-16 15:39
Right.  In all cases here the servers hand out RRsets whose existence is denied by other served RRsets.  A few of the [NSEC3 cases](https://github.com/dns-violations/dns-violations/blob/master/2018/DVE-2018-0003.md) have been investigated deeper, and those were all caused by one commercial solution deployed on multiple places.  I don't know how those NSEC cases can originate.

**Comment by cdeccio** [comment] 2020-06-16 19:15
![Screen Shot 2020-06-16 at 1 12 09 PM](https://user-images.githubusercontent.com/3991892/84818271-7ab71300-afd3-11ea-865a-991b805e2d56.png)

**Comment by pspacek** [comment] 2020-06-17 06:52
Hi everyone. Detailed explanation why behavior on www.csas.cz is a problem can be found at https://en.blog.nic.cz/2019/07/10/error-in-dnssec-implementation-on-f5-big-ip-load-balancers/

In short it breaks DNS resolving for resolvers which implement RFC 8198, and that is becoming more common.

@cdeccio Could you please add check which raises "red error" if such inconsistency is detected? It would help to detect broken systems and get the fixed.

Thanks!

**Comment by cdeccio** [comment] 2020-06-19 16:21
> @cdeccio Could you please add check which raises "red error" if such inconsistency is detected? It would help to detect broken systems and get the fixed.
>

Working on it.  I have a solution that I'm now testing for robustness (wish I had a better system for regression testing...)

**Comment by pspacek** [comment] 2020-06-22 06:02
FYI you might be interested in https://gitlab.labs.nic.cz/knot/deckard - that's a test tool designed for regression testing DNS resolvers.

**Comment by cdeccio** [comment] 2020-06-25 05:46
I've done some preliminary work on this, but it's not as straight-forward as I might have thought.  There are some clear cases, and then there are some weird cases.  I'm documenting a few here because I'm looking for some feedback.

Clear example of NSEC contradicting existing record:

Query for non-existent record results in NODATA response with NSEC record linking to itself and bitmap with no A:
```
$ dig +dnssec @ns1.eop-net.com 2.1.live-demo.org cname | grep 'IN[[:space:]]\+NSEC'
2.1.live-demo.org.	1200	IN	NSEC	2.1.live-demo.org. NS SOA RRSIG NSEC
```

Query for same name but type A results in NOERROR response, contradicting the previous NSEC record:
```
$ dig +dnssec @ns1.eop-net.com 2.1.live-demo.org a | grep 'IN[[:space:]]\+A'
;2.1.live-demo.org.		IN	A
2.1.live-demo.org.	1200	IN	A	148.251.137.238
2.1.live-demo.org.	1200	IN	A	136.243.101.142
2.1.live-demo.org.	1200	IN	A	148.251.184.8
2.1.live-demo.org.	1200	IN	A	144.76.44.207
2.1.live-demo.org.	1200	IN	A	136.243.13.216
```

There is some other weirdness with this domain, but I haven't yet put my finger on it.  The servers generate delegation chains and the corresponding DNSSEC chains dynamically.  For example, 3.2.1.live-demo.org.

This one is weird:

First consider the NSEC3 hashes:

$ /usr/sbin/nsec3hash 9E4D6A980DF0F9B3 1 10 blahblah.parsemail.org
UMGUUFQTOU7JKGBIE3H8099OKN1J7Q6N (salt=9E4D6A980DF0F9B3, hash=1, iterations=10)
$ /usr/sbin/nsec3hash 9E4D6A980DF0F9B3 1 10 parsemail.org
BOHBVRR92K6NC4IOAVVQ359FFHAEJTRB (salt=9E4D6A980DF0F9B3, hash=1, iterations=10)
$ /usr/sbin/nsec3hash 9E4D6A980DF0F9B3 1 10 *.parsemail.org
BLVA7DPA6ND4GHEU29BP771E4R1VIUNK (salt=9E4D6A980DF0F9B3, hash=1, iterations=10)

Now:

```
$ dig +dnssec @bran.grepular.com blahblah.parsemail.org | grep 'IN[[:space:]]\+NSEC'
bohbvrr92k6nc4ioavvq359ffhaejtrb.parsemail.org.	10800 IN NSEC3 1 0 10 9E4D6A980DF0F9B3 HR0DA3TR9VCMSVURGFJ1M73R3C20SK6Q A NS SOA MX TXT RRSIG DNSKEY NSEC3PARAM CAA
spth9sg6eju8hrvma2616dffbs8b8oa9.parsemail.org.	10800 IN NSEC3 1 0 10 9E4D6A980DF0F9B3 8CJ31BVN6G6KNO5QP3VH1CJUBTJON5RB TXT RRSIG
952r8opqa4mqrm3humrhqb077mufirtq.parsemail.org.	10800 IN NSEC3 1 0 10 9E4D6A980DF0F9B3 BOHBVRR92K6NC4IOAVVQ359FFHAEJTRB
```

That response seems to be in order, but this one has issues:

```
$ dig +dnssec @ned.parsemail.org blahblah.parsemail.org | grep 'IN[[:space:]]\+NSEC'
bohbvrr92k6nc4ioavvq359ffhaejtrb.parsemail.org.	10800 IN NSEC3 1 0 10 9E4D6A980DF0F9B3 HR0DA3TR9VCMSVURGFJ1M73R3C20SK6Q A NS SOA MX TXT RRSIG DNSKEY NSEC3PARAM CAA
spth9sg6eju8hrvma2616dffbs8b8oa9.parsemail.org.	10800 IN NSEC3 1 0 10 9E4D6A980DF0F9B3 8CJ31BVN6G6KNO5QP3VH1CJUBTJON5RB TXT RRSIG
952r8opqa4mqrm3humrhqb077mufirtq.parsemail.org.	10800 IN NSEC3 1 0 10 9E4D6A980DF0F9B3 HR0DA3TR9VCMSVURGFJ1M73R3C20SK6Q
```

It both confirms the existence of parsemail.org (i.e., with the `bohbvrr92k6nc4ioavvq359ffhaejtrb.parsemail.org` record) and denies the existence of parsemail.org (i.e., with the `952r8opqa4mqrm3humrhqb077mufirtq.parsemail.org` record).  This almost seems like a whole different class of error.

Thoughts on either of these?  Oh, and there are many more.  These are only the first two cases I've made it through.

**Comment by pspacek** [comment] 2020-06-25 06:19
This one breaks resolution for RFC8198 compliant resolvers:
> ```
> $ dig +dnssec @ns1.eop-net.com 2.1.live-demo.org cname | grep 'IN[[:space:]]\+NSEC'
> 2.1.live-demo.org.	1200	IN	NSEC	2.1.live-demo.org. NS SOA RRSIG NSEC
> ```
> 
> 
> Query for same name but type A results in NOERROR response, contradicting the previous NSEC record:
> 
> ```
> $ dig +dnssec @ns1.eop-net.com 2.1.live-demo.org a | grep 'IN[[:space:]]\+A'
> ;2.1.live-demo.org.		IN	A
> 2.1.live-demo.org.	1200	IN	A	148.251.137.238
> 2.1.live-demo.org.	1200	IN	A	136.243.101.142
> 2.1.live-demo.org.	1200	IN	A	148.251.184.8
> 2.1.live-demo.org.	1200	IN	A	144.76.44.207
> 2.1.live-demo.org.	1200	IN	A	136.243.13.216
> ```

In general the problem arises if proof-of-nonexistence claims that something does not exist _but_ at the same time authoritative servers actually send back answer when asked for it.

It is _not_ a problem if proof claims that something does exist but the servers send back reply with new proof of nonexistence which claims it does not exist anymore (that's basically the same as changing data on auth side). So this is an example where it is okay:

```
$ dig cloudflare.com TYPE1234 +dnssec

; <<>> DiG 9.16.4 <<>> cloudflare.com TYPE1234 +dnssec
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 12533
;; flags: qr rd ra ad; QUERY: 1, ANSWER: 0, AUTHORITY: 4, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags: do; udp: 4096
;; QUESTION SECTION:
;cloudflare.com.			IN	TYPE1234

;; AUTHORITY SECTION:
cloudflare.com.		300	IN	SOA	ns3.cloudflare.com. dns.cloudflare.com. 2034466070 10000 2400 604800 300
cloudflare.com.		300	IN	NSEC	\000.cloudflare.com. A NS SOA HINFO MX TXT AAAA LOC SRV CERT SSHFP RRSIG NSEC DNSKEY TLSA HIP CDS CDNSKEY OPENPGPKEY SPF CAA
cloudflare.com.		300	IN	RRSIG	SOA 13 2 300 20200626071831 20200624051831 34505 cloudflare.com. BOLau1WOpjyIAjeT7tE04EHhXEDaiu6fHl9HuB8MbBkWydm9pJZYr93w TB6wOLPhFOi3z/KLjrAZtQfroWlQaQ==
cloudflare.com.		300	IN	RRSIG	NSEC 13 2 300 20200626071831 20200624051831 34505 cloudflare.com. FONDo017g1iy6/XCoa/TFXK3dE5oDXMOXxh07MPuRUk5jXWeDubB0xM3 6Vzj3uVPpSHDLlY5og3wVVigVXu32A==

$  dig cloudflare.com TLSA +dnssec

; <<>> DiG 9.16.4 <<>> cloudflare.com TLSA +dnssec
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 43400
;; flags: qr rd ra ad; QUERY: 1, ANSWER: 0, AUTHORITY: 4, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags: do; udp: 4096
;; QUESTION SECTION:
;cloudflare.com.			IN	TLSA

;; AUTHORITY SECTION:
cloudflare.com.		300	IN	SOA	ns3.cloudflare.com. dns.cloudflare.com. 2034466070 10000 2400 604800 300
cloudflare.com.		300	IN	NSEC	\000.cloudflare.com. A NS SOA HINFO MX TXT AAAA LOC SRV CERT SSHFP RRSIG NSEC DNSKEY HIP CDS CDNSKEY OPENPGPKEY SPF CAA
cloudflare.com.		300	IN	RRSIG	SOA 13 2 300 20200626071852 20200624051852 34505 cloudflare.com. /DpEZQRHgNiNysY4DC1z8uvU86HCPeLuWDSibpDNFNfFo4CNFFDto7K1 WFGnw/YTGZRc1rwvTixZjcWVVxI/RA==
cloudflare.com.		300	IN	RRSIG	NSEC 13 2 300 20200626071852 20200624051852 34505 cloudflare.com. 3600yvDiRrEc/dklOPAE+fjZeT5d/D4YWJ0LgswhdkdHAEUqb8O0Z0HA Fa/bxEKFSyfbgLFGPXDfF1Ki6joRHA==
```

I will look at the rest later.

**Comment by cdeccio** [comment] 2020-10-08 01:32
I (obviously) had to put this away for a while, but I've created a branch with the commits, but it needs more testing. 7bcfe95d

**Comment by pspacek** [comment] 2020-10-09 18:08
I'm glad you found time for it. At the moment I'm swamped and cannot lend a hand, sorry!

**Comment by cdeccio** [comment] 2020-12-09 00:47
Fixed in #68

**Closed by cdeccio** 2020-12-09 00:47 UTC

**Comment by pspacek** [comment] 2020-12-14 18:31
Cool! Thank you so much!

Do you have an idea when it will get deployed to dnsviz.net? Or maybe @jelu knows?

I'm checking one broken domain, www.csas.cz AAAA which sends proof-of-nonexistence for A records when queries for AAAA, but it is not detected yet: https://dnsviz.net/d/www.csas.cz/X9euug/dnssec/

**Comment by jelu** [comment] 2020-12-15 07:55
> Or maybe @jelu knows?
Sorry @pspacek, this is not on my table.

**Comment by cdeccio** [comment] 2020-12-15 14:25
> Cool! Thank you so much!
> 
> Do you have an idea when it will get deployed to dnsviz.net? Or maybe @jelu knows?
> 

Working on it.  Will let you know.

**Comment by cdeccio** [comment] 2020-12-16 22:42
https://dnsviz.net/d/www.csas.cz/X9euug/dnssec/?rr=all&a=all&ds=all&doe=on&ta=.&tk=
(sorry, it only appears with doe checked, at the moment)

**Comment by pspacek** [comment] 2021-11-26 19:02
@cdeccio Would it be possible to enable it by default? In my experience it works pretty well and it's pity that people are not warned about this when it breaks domains in practice. Thank you!
